services:
  - type: web
    name: my-flask-app
    env: python
    plan: starter
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: VERIFY_TOKEN
        value: your_default_verify_token
      - key: WHATSAPP_GROUP_ID
        value: your_default_group_id
      - key: PORT
        value: 5000
